import { expect, test } from "@playwright/test"
import { capabilityContent, seedCapabilityNote } from "./editor-capability-seed"

test("大小写、全词、独立高亮与替换数量可用，撤销后计数刷新", async ({ page }) => {
  const original = "cat Cat scatter cat_ cat.\n\n下一段 cat"
  await seedCapabilityNote(page, original)
  const workspace = page.locator(".note-editor:visible"), editor = workspace.locator(".cm-content")
  await editor.press("ControlOrMeta+f")
  const query = workspace.getByLabel("查找当前笔记"), result = workspace.locator(".editor-find-field [aria-live]")
  await query.fill("cat")
  await expect(result).toHaveText("1/6")
  await expect(workspace.locator(".cm-note-find-match, .cm-note-find-current")).toHaveCount(6)
  await workspace.getByRole("button", { name: "区分大小写", exact: true }).click()
  await expect(result).toHaveText("1/5")
  await workspace.getByRole("button", { name: "全词匹配", exact: true }).click()
  await expect(result).toHaveText("1/3")
  await workspace.getByLabel("替换为").fill("dog")
  await workspace.getByRole("button", { name: "全部", exact: true }).click()
  await expect(workspace.getByRole("status").filter({ hasText: "已替换 3 处" })).toBeVisible()
  await expect.poll(() => capabilityContent(page)).toBe("dog Cat scatter cat_ dog.\n\n下一段 dog")
  await editor.press("ControlOrMeta+z")
  await expect(result).toHaveText(/\/3$/)
  await expect.poll(() => capabilityContent(page)).toBe(original)
  await workspace.getByRole("button", { name: "关闭查找", exact: true }).click()
  await expect(workspace.locator(".cm-note-find-match, .cm-note-find-current")).toHaveCount(0)
  await expect.poll(() => capabilityContent(page)).toBe(original)
})

test("仅原选区固定在打开前的范围，替换和撤销不波及选区外", async ({ page }) => {
  const original = "cat Cat scatter cat_ cat.\n\n选区外 cat"
  await seedCapabilityNote(page, original)
  const workspace = page.locator(".note-editor:visible"), editor = workspace.locator(".cm-content")
  await editor.press("ControlOrMeta+Home")
  await editor.press("Shift+End")
  await editor.press("ControlOrMeta+f")
  await workspace.getByLabel("查找当前笔记").fill("cat")
  await workspace.getByRole("button", { name: "仅原选区", exact: true }).click()
  await workspace.getByRole("button", { name: "全词匹配", exact: true }).click()
  await expect(workspace.locator(".editor-find-field [aria-live]")).toHaveText("1/3")
  await workspace.getByLabel("替换为").fill("猫")
  await workspace.getByRole("button", { name: "全部", exact: true }).click()
  await expect.poll(() => capabilityContent(page)).toBe("猫 猫 scatter cat_ 猫.\n\n选区外 cat")
  await editor.press("ControlOrMeta+z")
  await expect.poll(() => capabilityContent(page)).toBe(original)
  await expect(workspace.locator(".editor-find-field [aria-live]")).toHaveText(/\/3$/)
})

test("表格匹配格可见高亮，查找和替换不破坏网格编辑", async ({ page }) => {
  const original = "正文\n\n| 名称 | 备注 |\n| --- | --- |\n| **cat** | cat_ |\n| dog | cat |\n\n结尾"
  await seedCapabilityNote(page, original)
  const workspace = page.locator(".note-editor:visible"), table = workspace.locator(".cm-md-table")
  await expect(table).toBeVisible()
  await workspace.locator(".cm-content").press("ControlOrMeta+f")
  await workspace.getByLabel("查找当前笔记").fill("cat")
  await workspace.getByRole("button", { name: "全词匹配", exact: true }).click()
  await expect(table.locator('[data-note-find]')).toHaveCount(2)
  await workspace.getByLabel("替换为").fill("猫")
  await workspace.getByRole("button", { name: "全部", exact: true }).click()
  await expect(table.locator('[data-note-find]')).toHaveCount(0)
  await expect(table.locator("tbody tr")).toHaveCount(2)
  await expect.poll(() => capabilityContent(page)).toContain("| **猫** | cat_ |")
  await workspace.getByRole("button", { name: "关闭查找", exact: true }).click()
  await table.getByText("猫", { exact: true }).first().click()
  const input = table.locator("textarea")
  await input.fill("**猫**续写")
  await input.press("Tab")
  await expect.poll(() => capabilityContent(page)).toContain("**猫**续写")
})
