import { expect, test } from "@playwright/test"
import { capabilityContent, seedCapabilityNote } from "./editor-capability-seed"

test("斜杠菜单可插入公式并继续编辑，保存和撤销保持完整块", async ({ page }) => {
  await seedCapabilityNote(page, "正文\n\n")
  const workspace = page.locator(".note-editor:visible"), editor = workspace.locator(".cm-content")
  await editor.press("ControlOrMeta+End")
  await editor.pressSequentially("/math")
  await expect(workspace.getByRole("listbox", { name: "插入内容" })).toBeVisible()
  await editor.press("Enter")
  const textarea = workspace.locator(".cm-md-rich-editor textarea")
  await expect(textarea).toBeVisible()
  await textarea.fill("$$\na+b\n$$")
  await textarea.press("ControlOrMeta+Enter")
  await expect.poll(() => capabilityContent(page)).toContain("$$\na+b\n$$")
  await editor.press("ControlOrMeta+z")
  await expect.poll(() => capabilityContent(page)).toContain("x^2 + y^2 = z^2")
  await editor.press("ControlOrMeta+z")
  await expect.poll(() => capabilityContent(page)).toBe("正文\n\n/math")
})

test("工具栏插入脚注和模板，取消斜杠菜单保留普通文本", async ({ page, isMobile }) => {
  await seedCapabilityNote(page, "正文[^note-1]\n\n[^note-1]: 已有\n\n")
  const workspace = page.locator(".note-editor:visible"), editor = workspace.locator(".cm-content")
  await editor.press("ControlOrMeta+End")
  const menu = workspace.getByRole("button", { name: isMobile ? "更多格式" : "插入内容", exact: true })
  await menu.click()
  await workspace.getByRole("menuitem", { name: "脚注", exact: true }).click()
  await expect.poll(() => capabilityContent(page)).toContain("[^note-2]: 脚注内容")
  await editor.press("ControlOrMeta+End")
  await menu.click()
  await workspace.getByRole("menuitem", { name: "会议模板", exact: true }).click()
  await expect.poll(() => capabilityContent(page)).toContain("### 后续行动")
  await editor.press("ControlOrMeta+End")
  await editor.pressSequentially("/mermaid")
  await expect(workspace.getByRole("listbox", { name: "插入内容" })).toBeVisible()
  await editor.press("Escape")
  await expect(workspace.getByRole("listbox", { name: "插入内容" })).toBeHidden()
  await expect.poll(() => capabilityContent(page)).toContain("/mermaid")
})

test("中文组合确认不触发插入，图表和提示块插入后打开编辑入口", async ({ page, isMobile }) => {
  await seedCapabilityNote(page, "正文\n\n")
  const workspace = page.locator(".note-editor:visible"), editor = workspace.locator(".cm-content")
  await editor.press("ControlOrMeta+End")
  await editor.pressSequentially("/math")
  await editor.dispatchEvent("compositionstart")
  await editor.dispatchEvent("keydown", { key: "Enter", isComposing: true, keyCode: 229 })
  await editor.dispatchEvent("compositionend")
  await expect.poll(() => capabilityContent(page)).toContain("/math")
  await editor.press("Escape")
  const menu = workspace.getByRole("button", { name: isMobile ? "更多格式" : "插入内容", exact: true })
  await editor.press("ControlOrMeta+End")
  await editor.press("Enter")
  await menu.click()
  await workspace.getByRole("menuitem", { name: "Mermaid 图表", exact: true }).click()
  await expect(workspace.locator(".cm-md-rich-editor textarea")).toBeVisible()
  await workspace.locator(".cm-md-rich-editor textarea").press("Escape")
  await editor.press("ControlOrMeta+End")
  await menu.click()
  await workspace.getByRole("menuitem", { name: "提示块", exact: true }).click()
  await expect(workspace.locator(".cm-md-compat textarea")).toBeVisible()
})
